version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-vuepress
    versions:
    - 3.1.0
    - 3.2.0
  - dependency-name: vuepress
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
